// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2LMessage.proto

package auto.proto;

public final class C2LMessageProto {
  private C2LMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2LMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:C2LMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 contentMsgType = 1;</code>
     */
    boolean hasContentMsgType();
    /**
     * <code>required int32 contentMsgType = 1;</code>
     */
    int getContentMsgType();

    /**
     * <code>required bytes contentMsg = 2;</code>
     */
    boolean hasContentMsg();
    /**
     * <code>required bytes contentMsg = 2;</code>
     */
    com.google.protobuf.ByteString getContentMsg();
  }
  /**
   * Protobuf type {@code C2LMessage}
   */
  public  static final class C2LMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:C2LMessage)
      C2LMessageOrBuilder {
    // Use C2LMessage.newBuilder() to construct.
    private C2LMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2LMessage() {
      contentMsgType_ = 0;
      contentMsg_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2LMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              contentMsgType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              contentMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return auto.proto.C2LMessageProto.internal_static_C2LMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return auto.proto.C2LMessageProto.internal_static_C2LMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              auto.proto.C2LMessageProto.C2LMessage.class, auto.proto.C2LMessageProto.C2LMessage.Builder.class);
    }

    private int bitField0_;
    public static final int CONTENTMSGTYPE_FIELD_NUMBER = 1;
    private int contentMsgType_;
    /**
     * <code>required int32 contentMsgType = 1;</code>
     */
    public boolean hasContentMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 contentMsgType = 1;</code>
     */
    public int getContentMsgType() {
      return contentMsgType_;
    }

    public static final int CONTENTMSG_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString contentMsg_;
    /**
     * <code>required bytes contentMsg = 2;</code>
     */
    public boolean hasContentMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes contentMsg = 2;</code>
     */
    public com.google.protobuf.ByteString getContentMsg() {
      return contentMsg_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasContentMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContentMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, contentMsgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, contentMsg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, contentMsgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, contentMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof auto.proto.C2LMessageProto.C2LMessage)) {
        return super.equals(obj);
      }
      auto.proto.C2LMessageProto.C2LMessage other = (auto.proto.C2LMessageProto.C2LMessage) obj;

      boolean result = true;
      result = result && (hasContentMsgType() == other.hasContentMsgType());
      if (hasContentMsgType()) {
        result = result && (getContentMsgType()
            == other.getContentMsgType());
      }
      result = result && (hasContentMsg() == other.hasContentMsg());
      if (hasContentMsg()) {
        result = result && getContentMsg()
            .equals(other.getContentMsg());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasContentMsgType()) {
        hash = (37 * hash) + CONTENTMSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getContentMsgType();
      }
      if (hasContentMsg()) {
        hash = (37 * hash) + CONTENTMSG_FIELD_NUMBER;
        hash = (53 * hash) + getContentMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static auto.proto.C2LMessageProto.C2LMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static auto.proto.C2LMessageProto.C2LMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static auto.proto.C2LMessageProto.C2LMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static auto.proto.C2LMessageProto.C2LMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static auto.proto.C2LMessageProto.C2LMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static auto.proto.C2LMessageProto.C2LMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static auto.proto.C2LMessageProto.C2LMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static auto.proto.C2LMessageProto.C2LMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static auto.proto.C2LMessageProto.C2LMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static auto.proto.C2LMessageProto.C2LMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(auto.proto.C2LMessageProto.C2LMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C2LMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C2LMessage)
        auto.proto.C2LMessageProto.C2LMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return auto.proto.C2LMessageProto.internal_static_C2LMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return auto.proto.C2LMessageProto.internal_static_C2LMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                auto.proto.C2LMessageProto.C2LMessage.class, auto.proto.C2LMessageProto.C2LMessage.Builder.class);
      }

      // Construct using auto.proto.C2LMessageProto.C2LMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        contentMsgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        contentMsg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return auto.proto.C2LMessageProto.internal_static_C2LMessage_descriptor;
      }

      public auto.proto.C2LMessageProto.C2LMessage getDefaultInstanceForType() {
        return auto.proto.C2LMessageProto.C2LMessage.getDefaultInstance();
      }

      public auto.proto.C2LMessageProto.C2LMessage build() {
        auto.proto.C2LMessageProto.C2LMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public auto.proto.C2LMessageProto.C2LMessage buildPartial() {
        auto.proto.C2LMessageProto.C2LMessage result = new auto.proto.C2LMessageProto.C2LMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.contentMsgType_ = contentMsgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.contentMsg_ = contentMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof auto.proto.C2LMessageProto.C2LMessage) {
          return mergeFrom((auto.proto.C2LMessageProto.C2LMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(auto.proto.C2LMessageProto.C2LMessage other) {
        if (other == auto.proto.C2LMessageProto.C2LMessage.getDefaultInstance()) return this;
        if (other.hasContentMsgType()) {
          setContentMsgType(other.getContentMsgType());
        }
        if (other.hasContentMsg()) {
          setContentMsg(other.getContentMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContentMsgType()) {
          return false;
        }
        if (!hasContentMsg()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        auto.proto.C2LMessageProto.C2LMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (auto.proto.C2LMessageProto.C2LMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int contentMsgType_ ;
      /**
       * <code>required int32 contentMsgType = 1;</code>
       */
      public boolean hasContentMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 contentMsgType = 1;</code>
       */
      public int getContentMsgType() {
        return contentMsgType_;
      }
      /**
       * <code>required int32 contentMsgType = 1;</code>
       */
      public Builder setContentMsgType(int value) {
        bitField0_ |= 0x00000001;
        contentMsgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 contentMsgType = 1;</code>
       */
      public Builder clearContentMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        contentMsgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contentMsg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes contentMsg = 2;</code>
       */
      public boolean hasContentMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes contentMsg = 2;</code>
       */
      public com.google.protobuf.ByteString getContentMsg() {
        return contentMsg_;
      }
      /**
       * <code>required bytes contentMsg = 2;</code>
       */
      public Builder setContentMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        contentMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes contentMsg = 2;</code>
       */
      public Builder clearContentMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        contentMsg_ = getDefaultInstance().getContentMsg();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:C2LMessage)
    }

    // @@protoc_insertion_point(class_scope:C2LMessage)
    private static final auto.proto.C2LMessageProto.C2LMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new auto.proto.C2LMessageProto.C2LMessage();
    }

    public static auto.proto.C2LMessageProto.C2LMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2LMessage>
        PARSER = new com.google.protobuf.AbstractParser<C2LMessage>() {
      public C2LMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new C2LMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2LMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2LMessage> getParserForType() {
      return PARSER;
    }

    public auto.proto.C2LMessageProto.C2LMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .C2LMessageProtocolType PROTOCOL_TYPE = 1 [default = HEARTBEAT];</code>
     */
    boolean hasPROTOCOLTYPE();
    /**
     * <code>optional .C2LMessageProtocolType PROTOCOL_TYPE = 1 [default = HEARTBEAT];</code>
     */
    auto.proto.Enum.C2LMessageProtocolType getPROTOCOLTYPE();
  }
  /**
   * Protobuf type {@code HeartBeat}
   */
  public  static final class HeartBeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeat)
      HeartBeatOrBuilder {
    // Use HeartBeat.newBuilder() to construct.
    private HeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeat() {
      pROTOCOLTYPE_ = 100;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              auto.proto.Enum.C2LMessageProtocolType value = auto.proto.Enum.C2LMessageProtocolType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                pROTOCOLTYPE_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return auto.proto.C2LMessageProto.internal_static_HeartBeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return auto.proto.C2LMessageProto.internal_static_HeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              auto.proto.C2LMessageProto.HeartBeat.class, auto.proto.C2LMessageProto.HeartBeat.Builder.class);
    }

    private int bitField0_;
    public static final int PROTOCOL_TYPE_FIELD_NUMBER = 1;
    private int pROTOCOLTYPE_;
    /**
     * <code>optional .C2LMessageProtocolType PROTOCOL_TYPE = 1 [default = HEARTBEAT];</code>
     */
    public boolean hasPROTOCOLTYPE() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .C2LMessageProtocolType PROTOCOL_TYPE = 1 [default = HEARTBEAT];</code>
     */
    public auto.proto.Enum.C2LMessageProtocolType getPROTOCOLTYPE() {
      auto.proto.Enum.C2LMessageProtocolType result = auto.proto.Enum.C2LMessageProtocolType.valueOf(pROTOCOLTYPE_);
      return result == null ? auto.proto.Enum.C2LMessageProtocolType.HEARTBEAT : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, pROTOCOLTYPE_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, pROTOCOLTYPE_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof auto.proto.C2LMessageProto.HeartBeat)) {
        return super.equals(obj);
      }
      auto.proto.C2LMessageProto.HeartBeat other = (auto.proto.C2LMessageProto.HeartBeat) obj;

      boolean result = true;
      result = result && (hasPROTOCOLTYPE() == other.hasPROTOCOLTYPE());
      if (hasPROTOCOLTYPE()) {
        result = result && pROTOCOLTYPE_ == other.pROTOCOLTYPE_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPROTOCOLTYPE()) {
        hash = (37 * hash) + PROTOCOL_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + pROTOCOLTYPE_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static auto.proto.C2LMessageProto.HeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static auto.proto.C2LMessageProto.HeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static auto.proto.C2LMessageProto.HeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static auto.proto.C2LMessageProto.HeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static auto.proto.C2LMessageProto.HeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static auto.proto.C2LMessageProto.HeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static auto.proto.C2LMessageProto.HeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static auto.proto.C2LMessageProto.HeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static auto.proto.C2LMessageProto.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static auto.proto.C2LMessageProto.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(auto.proto.C2LMessageProto.HeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeat)
        auto.proto.C2LMessageProto.HeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return auto.proto.C2LMessageProto.internal_static_HeartBeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return auto.proto.C2LMessageProto.internal_static_HeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                auto.proto.C2LMessageProto.HeartBeat.class, auto.proto.C2LMessageProto.HeartBeat.Builder.class);
      }

      // Construct using auto.proto.C2LMessageProto.HeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pROTOCOLTYPE_ = 100;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return auto.proto.C2LMessageProto.internal_static_HeartBeat_descriptor;
      }

      public auto.proto.C2LMessageProto.HeartBeat getDefaultInstanceForType() {
        return auto.proto.C2LMessageProto.HeartBeat.getDefaultInstance();
      }

      public auto.proto.C2LMessageProto.HeartBeat build() {
        auto.proto.C2LMessageProto.HeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public auto.proto.C2LMessageProto.HeartBeat buildPartial() {
        auto.proto.C2LMessageProto.HeartBeat result = new auto.proto.C2LMessageProto.HeartBeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pROTOCOLTYPE_ = pROTOCOLTYPE_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof auto.proto.C2LMessageProto.HeartBeat) {
          return mergeFrom((auto.proto.C2LMessageProto.HeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(auto.proto.C2LMessageProto.HeartBeat other) {
        if (other == auto.proto.C2LMessageProto.HeartBeat.getDefaultInstance()) return this;
        if (other.hasPROTOCOLTYPE()) {
          setPROTOCOLTYPE(other.getPROTOCOLTYPE());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        auto.proto.C2LMessageProto.HeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (auto.proto.C2LMessageProto.HeartBeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int pROTOCOLTYPE_ = 100;
      /**
       * <code>optional .C2LMessageProtocolType PROTOCOL_TYPE = 1 [default = HEARTBEAT];</code>
       */
      public boolean hasPROTOCOLTYPE() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .C2LMessageProtocolType PROTOCOL_TYPE = 1 [default = HEARTBEAT];</code>
       */
      public auto.proto.Enum.C2LMessageProtocolType getPROTOCOLTYPE() {
        auto.proto.Enum.C2LMessageProtocolType result = auto.proto.Enum.C2LMessageProtocolType.valueOf(pROTOCOLTYPE_);
        return result == null ? auto.proto.Enum.C2LMessageProtocolType.HEARTBEAT : result;
      }
      /**
       * <code>optional .C2LMessageProtocolType PROTOCOL_TYPE = 1 [default = HEARTBEAT];</code>
       */
      public Builder setPROTOCOLTYPE(auto.proto.Enum.C2LMessageProtocolType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        pROTOCOLTYPE_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .C2LMessageProtocolType PROTOCOL_TYPE = 1 [default = HEARTBEAT];</code>
       */
      public Builder clearPROTOCOLTYPE() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pROTOCOLTYPE_ = 100;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartBeat)
    }

    // @@protoc_insertion_point(class_scope:HeartBeat)
    private static final auto.proto.C2LMessageProto.HeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new auto.proto.C2LMessageProto.HeartBeat();
    }

    public static auto.proto.C2LMessageProto.HeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeat>() {
      public HeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeartBeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeat> getParserForType() {
      return PARSER;
    }

    public auto.proto.C2LMessageProto.HeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C2LMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_C2LMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020C2LMessage.proto\032\nenum.proto\"8\n\nC2LMes" +
      "sage\022\026\n\016contentMsgType\030\001 \002(\005\022\022\n\ncontentM" +
      "sg\030\002 \002(\014\"F\n\tHeartBeat\0229\n\rPROTOCOL_TYPE\030\001" +
      " \001(\0162\027.C2LMessageProtocolType:\tHEARTBEAT" +
      "B\035\n\nauto.protoB\017C2LMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          auto.proto.Enum.getDescriptor(),
        }, assigner);
    internal_static_C2LMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_C2LMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_C2LMessage_descriptor,
        new java.lang.String[] { "ContentMsgType", "ContentMsg", });
    internal_static_HeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeat_descriptor,
        new java.lang.String[] { "PROTOCOLTYPE", });
    auto.proto.Enum.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
