// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum.proto

package auto.proto;

public final class Enum {
  private Enum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code C2LMessageProtocolType}
   */
  public enum C2LMessageProtocolType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HEARTBEAT = 100;</code>
     */
    HEARTBEAT(100),
    ;

    /**
     * <code>HEARTBEAT = 100;</code>
     */
    public static final int HEARTBEAT_VALUE = 100;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static C2LMessageProtocolType valueOf(int value) {
      return forNumber(value);
    }

    public static C2LMessageProtocolType forNumber(int value) {
      switch (value) {
        case 100: return HEARTBEAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<C2LMessageProtocolType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        C2LMessageProtocolType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<C2LMessageProtocolType>() {
            public C2LMessageProtocolType findValueByNumber(int number) {
              return C2LMessageProtocolType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return auto.proto.Enum.getDescriptor().getEnumTypes().get(0);
    }

    private static final C2LMessageProtocolType[] VALUES = values();

    public static C2LMessageProtocolType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private C2LMessageProtocolType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:C2LMessageProtocolType)
  }

  /**
   * Protobuf enum {@code L2GMessageProtocolType}
   */
  public enum L2GMessageProtocolType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CONNECTBROKEN = 200;</code>
     */
    CONNECTBROKEN(200),
    ;

    /**
     * <code>CONNECTBROKEN = 200;</code>
     */
    public static final int CONNECTBROKEN_VALUE = 200;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static L2GMessageProtocolType valueOf(int value) {
      return forNumber(value);
    }

    public static L2GMessageProtocolType forNumber(int value) {
      switch (value) {
        case 200: return CONNECTBROKEN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<L2GMessageProtocolType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        L2GMessageProtocolType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<L2GMessageProtocolType>() {
            public L2GMessageProtocolType findValueByNumber(int number) {
              return L2GMessageProtocolType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return auto.proto.Enum.getDescriptor().getEnumTypes().get(1);
    }

    private static final L2GMessageProtocolType[] VALUES = values();

    public static L2GMessageProtocolType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private L2GMessageProtocolType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:L2GMessageProtocolType)
  }

  /**
   * Protobuf enum {@code PROTO_KEY}
   */
  public enum PROTO_KEY
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Role_Key = 500;</code>
     */
    Role_Key(500),
    /**
     * <code>C2SRoleInfo_Key = 501;</code>
     */
    C2SRoleInfo_Key(501),
    /**
     * <code>C2SComplexTest_Key = 502;</code>
     */
    C2SComplexTest_Key(502),
    /**
     * <code>C2SAddItem_Key = 503;</code>
     */
    C2SAddItem_Key(503),
    ;

    /**
     * <code>Role_Key = 500;</code>
     */
    public static final int Role_Key_VALUE = 500;
    /**
     * <code>C2SRoleInfo_Key = 501;</code>
     */
    public static final int C2SRoleInfo_Key_VALUE = 501;
    /**
     * <code>C2SComplexTest_Key = 502;</code>
     */
    public static final int C2SComplexTest_Key_VALUE = 502;
    /**
     * <code>C2SAddItem_Key = 503;</code>
     */
    public static final int C2SAddItem_Key_VALUE = 503;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PROTO_KEY valueOf(int value) {
      return forNumber(value);
    }

    public static PROTO_KEY forNumber(int value) {
      switch (value) {
        case 500: return Role_Key;
        case 501: return C2SRoleInfo_Key;
        case 502: return C2SComplexTest_Key;
        case 503: return C2SAddItem_Key;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PROTO_KEY>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PROTO_KEY> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PROTO_KEY>() {
            public PROTO_KEY findValueByNumber(int number) {
              return PROTO_KEY.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return auto.proto.Enum.getDescriptor().getEnumTypes().get(2);
    }

    private static final PROTO_KEY[] VALUES = values();

    public static PROTO_KEY valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PROTO_KEY(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PROTO_KEY)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nenum.proto*\'\n\026C2LMessageProtocolType\022\r" +
      "\n\tHEARTBEAT\020d*,\n\026L2GMessageProtocolType\022" +
      "\022\n\rCONNECTBROKEN\020\310\001*^\n\tPROTO_KEY\022\r\n\010Role" +
      "_Key\020\364\003\022\024\n\017C2SRoleInfo_Key\020\365\003\022\027\n\022C2SComp" +
      "lexTest_Key\020\366\003\022\023\n\016C2SAddItem_Key\020\367\003B\022\n\na" +
      "uto.protoB\004Enum"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
