// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: G2LMessage.proto

package auto.proto;

public final class G2LMessageProto {
  private G2LMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface G2LMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:G2LMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string client2LinkChannelId = 1;</code>
     */
    boolean hasClient2LinkChannelId();
    /**
     * <code>required string client2LinkChannelId = 1;</code>
     */
    java.lang.String getClient2LinkChannelId();
    /**
     * <code>required string client2LinkChannelId = 1;</code>
     */
    com.google.protobuf.ByteString
        getClient2LinkChannelIdBytes();

    /**
     * <code>required int32 contentMsgType = 2;</code>
     */
    boolean hasContentMsgType();
    /**
     * <code>required int32 contentMsgType = 2;</code>
     */
    int getContentMsgType();

    /**
     * <code>required bytes contentMsg = 3;</code>
     */
    boolean hasContentMsg();
    /**
     * <code>required bytes contentMsg = 3;</code>
     */
    com.google.protobuf.ByteString getContentMsg();
  }
  /**
   * Protobuf type {@code G2LMessage}
   */
  public  static final class G2LMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:G2LMessage)
      G2LMessageOrBuilder {
    // Use G2LMessage.newBuilder() to construct.
    private G2LMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private G2LMessage() {
      client2LinkChannelId_ = "";
      contentMsgType_ = 0;
      contentMsg_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private G2LMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              client2LinkChannelId_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              contentMsgType_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              contentMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return auto.proto.G2LMessageProto.internal_static_G2LMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return auto.proto.G2LMessageProto.internal_static_G2LMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              auto.proto.G2LMessageProto.G2LMessage.class, auto.proto.G2LMessageProto.G2LMessage.Builder.class);
    }

    private int bitField0_;
    public static final int CLIENT2LINKCHANNELID_FIELD_NUMBER = 1;
    private volatile java.lang.Object client2LinkChannelId_;
    /**
     * <code>required string client2LinkChannelId = 1;</code>
     */
    public boolean hasClient2LinkChannelId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string client2LinkChannelId = 1;</code>
     */
    public java.lang.String getClient2LinkChannelId() {
      java.lang.Object ref = client2LinkChannelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          client2LinkChannelId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string client2LinkChannelId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClient2LinkChannelIdBytes() {
      java.lang.Object ref = client2LinkChannelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        client2LinkChannelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTMSGTYPE_FIELD_NUMBER = 2;
    private int contentMsgType_;
    /**
     * <code>required int32 contentMsgType = 2;</code>
     */
    public boolean hasContentMsgType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 contentMsgType = 2;</code>
     */
    public int getContentMsgType() {
      return contentMsgType_;
    }

    public static final int CONTENTMSG_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString contentMsg_;
    /**
     * <code>required bytes contentMsg = 3;</code>
     */
    public boolean hasContentMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes contentMsg = 3;</code>
     */
    public com.google.protobuf.ByteString getContentMsg() {
      return contentMsg_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasClient2LinkChannelId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContentMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContentMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, client2LinkChannelId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, contentMsgType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, contentMsg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, client2LinkChannelId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, contentMsgType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, contentMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof auto.proto.G2LMessageProto.G2LMessage)) {
        return super.equals(obj);
      }
      auto.proto.G2LMessageProto.G2LMessage other = (auto.proto.G2LMessageProto.G2LMessage) obj;

      boolean result = true;
      result = result && (hasClient2LinkChannelId() == other.hasClient2LinkChannelId());
      if (hasClient2LinkChannelId()) {
        result = result && getClient2LinkChannelId()
            .equals(other.getClient2LinkChannelId());
      }
      result = result && (hasContentMsgType() == other.hasContentMsgType());
      if (hasContentMsgType()) {
        result = result && (getContentMsgType()
            == other.getContentMsgType());
      }
      result = result && (hasContentMsg() == other.hasContentMsg());
      if (hasContentMsg()) {
        result = result && getContentMsg()
            .equals(other.getContentMsg());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasClient2LinkChannelId()) {
        hash = (37 * hash) + CLIENT2LINKCHANNELID_FIELD_NUMBER;
        hash = (53 * hash) + getClient2LinkChannelId().hashCode();
      }
      if (hasContentMsgType()) {
        hash = (37 * hash) + CONTENTMSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getContentMsgType();
      }
      if (hasContentMsg()) {
        hash = (37 * hash) + CONTENTMSG_FIELD_NUMBER;
        hash = (53 * hash) + getContentMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static auto.proto.G2LMessageProto.G2LMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static auto.proto.G2LMessageProto.G2LMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static auto.proto.G2LMessageProto.G2LMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static auto.proto.G2LMessageProto.G2LMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static auto.proto.G2LMessageProto.G2LMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static auto.proto.G2LMessageProto.G2LMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static auto.proto.G2LMessageProto.G2LMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static auto.proto.G2LMessageProto.G2LMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static auto.proto.G2LMessageProto.G2LMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static auto.proto.G2LMessageProto.G2LMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(auto.proto.G2LMessageProto.G2LMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code G2LMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:G2LMessage)
        auto.proto.G2LMessageProto.G2LMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return auto.proto.G2LMessageProto.internal_static_G2LMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return auto.proto.G2LMessageProto.internal_static_G2LMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                auto.proto.G2LMessageProto.G2LMessage.class, auto.proto.G2LMessageProto.G2LMessage.Builder.class);
      }

      // Construct using auto.proto.G2LMessageProto.G2LMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        client2LinkChannelId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        contentMsgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        contentMsg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return auto.proto.G2LMessageProto.internal_static_G2LMessage_descriptor;
      }

      public auto.proto.G2LMessageProto.G2LMessage getDefaultInstanceForType() {
        return auto.proto.G2LMessageProto.G2LMessage.getDefaultInstance();
      }

      public auto.proto.G2LMessageProto.G2LMessage build() {
        auto.proto.G2LMessageProto.G2LMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public auto.proto.G2LMessageProto.G2LMessage buildPartial() {
        auto.proto.G2LMessageProto.G2LMessage result = new auto.proto.G2LMessageProto.G2LMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.client2LinkChannelId_ = client2LinkChannelId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.contentMsgType_ = contentMsgType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.contentMsg_ = contentMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof auto.proto.G2LMessageProto.G2LMessage) {
          return mergeFrom((auto.proto.G2LMessageProto.G2LMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(auto.proto.G2LMessageProto.G2LMessage other) {
        if (other == auto.proto.G2LMessageProto.G2LMessage.getDefaultInstance()) return this;
        if (other.hasClient2LinkChannelId()) {
          bitField0_ |= 0x00000001;
          client2LinkChannelId_ = other.client2LinkChannelId_;
          onChanged();
        }
        if (other.hasContentMsgType()) {
          setContentMsgType(other.getContentMsgType());
        }
        if (other.hasContentMsg()) {
          setContentMsg(other.getContentMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClient2LinkChannelId()) {
          return false;
        }
        if (!hasContentMsgType()) {
          return false;
        }
        if (!hasContentMsg()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        auto.proto.G2LMessageProto.G2LMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (auto.proto.G2LMessageProto.G2LMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object client2LinkChannelId_ = "";
      /**
       * <code>required string client2LinkChannelId = 1;</code>
       */
      public boolean hasClient2LinkChannelId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string client2LinkChannelId = 1;</code>
       */
      public java.lang.String getClient2LinkChannelId() {
        java.lang.Object ref = client2LinkChannelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            client2LinkChannelId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string client2LinkChannelId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClient2LinkChannelIdBytes() {
        java.lang.Object ref = client2LinkChannelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          client2LinkChannelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string client2LinkChannelId = 1;</code>
       */
      public Builder setClient2LinkChannelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        client2LinkChannelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string client2LinkChannelId = 1;</code>
       */
      public Builder clearClient2LinkChannelId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        client2LinkChannelId_ = getDefaultInstance().getClient2LinkChannelId();
        onChanged();
        return this;
      }
      /**
       * <code>required string client2LinkChannelId = 1;</code>
       */
      public Builder setClient2LinkChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        client2LinkChannelId_ = value;
        onChanged();
        return this;
      }

      private int contentMsgType_ ;
      /**
       * <code>required int32 contentMsgType = 2;</code>
       */
      public boolean hasContentMsgType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 contentMsgType = 2;</code>
       */
      public int getContentMsgType() {
        return contentMsgType_;
      }
      /**
       * <code>required int32 contentMsgType = 2;</code>
       */
      public Builder setContentMsgType(int value) {
        bitField0_ |= 0x00000002;
        contentMsgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 contentMsgType = 2;</code>
       */
      public Builder clearContentMsgType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        contentMsgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contentMsg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes contentMsg = 3;</code>
       */
      public boolean hasContentMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes contentMsg = 3;</code>
       */
      public com.google.protobuf.ByteString getContentMsg() {
        return contentMsg_;
      }
      /**
       * <code>required bytes contentMsg = 3;</code>
       */
      public Builder setContentMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        contentMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes contentMsg = 3;</code>
       */
      public Builder clearContentMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        contentMsg_ = getDefaultInstance().getContentMsg();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:G2LMessage)
    }

    // @@protoc_insertion_point(class_scope:G2LMessage)
    private static final auto.proto.G2LMessageProto.G2LMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new auto.proto.G2LMessageProto.G2LMessage();
    }

    public static auto.proto.G2LMessageProto.G2LMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<G2LMessage>
        PARSER = new com.google.protobuf.AbstractParser<G2LMessage>() {
      public G2LMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new G2LMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<G2LMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<G2LMessage> getParserForType() {
      return PARSER;
    }

    public auto.proto.G2LMessageProto.G2LMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_G2LMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_G2LMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020G2LMessage.proto\"V\n\nG2LMessage\022\034\n\024clie" +
      "nt2LinkChannelId\030\001 \002(\t\022\026\n\016contentMsgType" +
      "\030\002 \002(\005\022\022\n\ncontentMsg\030\003 \002(\014B\035\n\nauto.proto" +
      "B\017G2LMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_G2LMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_G2LMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_G2LMessage_descriptor,
        new java.lang.String[] { "Client2LinkChannelId", "ContentMsgType", "ContentMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
