// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: L2CMessage.proto

package auto.proto;

public final class L2CMessageProto {
  private L2CMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface L2CMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:L2CMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 contentMsgType = 1;</code>
     */
    boolean hasContentMsgType();
    /**
     * <code>required int32 contentMsgType = 1;</code>
     */
    int getContentMsgType();

    /**
     * <code>required bytes contentMsg = 2;</code>
     */
    boolean hasContentMsg();
    /**
     * <code>required bytes contentMsg = 2;</code>
     */
    com.google.protobuf.ByteString getContentMsg();
  }
  /**
   * Protobuf type {@code L2CMessage}
   */
  public  static final class L2CMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:L2CMessage)
      L2CMessageOrBuilder {
    // Use L2CMessage.newBuilder() to construct.
    private L2CMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private L2CMessage() {
      contentMsgType_ = 0;
      contentMsg_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private L2CMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              contentMsgType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              contentMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return auto.proto.L2CMessageProto.internal_static_L2CMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return auto.proto.L2CMessageProto.internal_static_L2CMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              auto.proto.L2CMessageProto.L2CMessage.class, auto.proto.L2CMessageProto.L2CMessage.Builder.class);
    }

    private int bitField0_;
    public static final int CONTENTMSGTYPE_FIELD_NUMBER = 1;
    private int contentMsgType_;
    /**
     * <code>required int32 contentMsgType = 1;</code>
     */
    public boolean hasContentMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 contentMsgType = 1;</code>
     */
    public int getContentMsgType() {
      return contentMsgType_;
    }

    public static final int CONTENTMSG_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString contentMsg_;
    /**
     * <code>required bytes contentMsg = 2;</code>
     */
    public boolean hasContentMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes contentMsg = 2;</code>
     */
    public com.google.protobuf.ByteString getContentMsg() {
      return contentMsg_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasContentMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContentMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, contentMsgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, contentMsg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, contentMsgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, contentMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof auto.proto.L2CMessageProto.L2CMessage)) {
        return super.equals(obj);
      }
      auto.proto.L2CMessageProto.L2CMessage other = (auto.proto.L2CMessageProto.L2CMessage) obj;

      boolean result = true;
      result = result && (hasContentMsgType() == other.hasContentMsgType());
      if (hasContentMsgType()) {
        result = result && (getContentMsgType()
            == other.getContentMsgType());
      }
      result = result && (hasContentMsg() == other.hasContentMsg());
      if (hasContentMsg()) {
        result = result && getContentMsg()
            .equals(other.getContentMsg());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasContentMsgType()) {
        hash = (37 * hash) + CONTENTMSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getContentMsgType();
      }
      if (hasContentMsg()) {
        hash = (37 * hash) + CONTENTMSG_FIELD_NUMBER;
        hash = (53 * hash) + getContentMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static auto.proto.L2CMessageProto.L2CMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static auto.proto.L2CMessageProto.L2CMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static auto.proto.L2CMessageProto.L2CMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static auto.proto.L2CMessageProto.L2CMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static auto.proto.L2CMessageProto.L2CMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static auto.proto.L2CMessageProto.L2CMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static auto.proto.L2CMessageProto.L2CMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static auto.proto.L2CMessageProto.L2CMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static auto.proto.L2CMessageProto.L2CMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static auto.proto.L2CMessageProto.L2CMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(auto.proto.L2CMessageProto.L2CMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code L2CMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:L2CMessage)
        auto.proto.L2CMessageProto.L2CMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return auto.proto.L2CMessageProto.internal_static_L2CMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return auto.proto.L2CMessageProto.internal_static_L2CMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                auto.proto.L2CMessageProto.L2CMessage.class, auto.proto.L2CMessageProto.L2CMessage.Builder.class);
      }

      // Construct using auto.proto.L2CMessageProto.L2CMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        contentMsgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        contentMsg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return auto.proto.L2CMessageProto.internal_static_L2CMessage_descriptor;
      }

      public auto.proto.L2CMessageProto.L2CMessage getDefaultInstanceForType() {
        return auto.proto.L2CMessageProto.L2CMessage.getDefaultInstance();
      }

      public auto.proto.L2CMessageProto.L2CMessage build() {
        auto.proto.L2CMessageProto.L2CMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public auto.proto.L2CMessageProto.L2CMessage buildPartial() {
        auto.proto.L2CMessageProto.L2CMessage result = new auto.proto.L2CMessageProto.L2CMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.contentMsgType_ = contentMsgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.contentMsg_ = contentMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof auto.proto.L2CMessageProto.L2CMessage) {
          return mergeFrom((auto.proto.L2CMessageProto.L2CMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(auto.proto.L2CMessageProto.L2CMessage other) {
        if (other == auto.proto.L2CMessageProto.L2CMessage.getDefaultInstance()) return this;
        if (other.hasContentMsgType()) {
          setContentMsgType(other.getContentMsgType());
        }
        if (other.hasContentMsg()) {
          setContentMsg(other.getContentMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContentMsgType()) {
          return false;
        }
        if (!hasContentMsg()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        auto.proto.L2CMessageProto.L2CMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (auto.proto.L2CMessageProto.L2CMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int contentMsgType_ ;
      /**
       * <code>required int32 contentMsgType = 1;</code>
       */
      public boolean hasContentMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 contentMsgType = 1;</code>
       */
      public int getContentMsgType() {
        return contentMsgType_;
      }
      /**
       * <code>required int32 contentMsgType = 1;</code>
       */
      public Builder setContentMsgType(int value) {
        bitField0_ |= 0x00000001;
        contentMsgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 contentMsgType = 1;</code>
       */
      public Builder clearContentMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        contentMsgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contentMsg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes contentMsg = 2;</code>
       */
      public boolean hasContentMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes contentMsg = 2;</code>
       */
      public com.google.protobuf.ByteString getContentMsg() {
        return contentMsg_;
      }
      /**
       * <code>required bytes contentMsg = 2;</code>
       */
      public Builder setContentMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        contentMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes contentMsg = 2;</code>
       */
      public Builder clearContentMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        contentMsg_ = getDefaultInstance().getContentMsg();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:L2CMessage)
    }

    // @@protoc_insertion_point(class_scope:L2CMessage)
    private static final auto.proto.L2CMessageProto.L2CMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new auto.proto.L2CMessageProto.L2CMessage();
    }

    public static auto.proto.L2CMessageProto.L2CMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<L2CMessage>
        PARSER = new com.google.protobuf.AbstractParser<L2CMessage>() {
      public L2CMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new L2CMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<L2CMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<L2CMessage> getParserForType() {
      return PARSER;
    }

    public auto.proto.L2CMessageProto.L2CMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_L2CMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_L2CMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020L2CMessage.proto\"8\n\nL2CMessage\022\026\n\016cont" +
      "entMsgType\030\001 \002(\005\022\022\n\ncontentMsg\030\002 \002(\014B\035\n\n" +
      "auto.protoB\017L2CMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_L2CMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_L2CMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_L2CMessage_descriptor,
        new java.lang.String[] { "ContentMsgType", "ContentMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
