// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum.proto

package tiny.auto.proto;

public final class Enum {
  private Enum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code PROTO_KEY}
   */
  public enum PROTO_KEY
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Role_Key = 100;</code>
     */
    Role_Key(100),
    /**
     * <code>C2SRoleInfo_Key = 101;</code>
     */
    C2SRoleInfo_Key(101),
    ;

    /**
     * <code>Role_Key = 100;</code>
     */
    public static final int Role_Key_VALUE = 100;
    /**
     * <code>C2SRoleInfo_Key = 101;</code>
     */
    public static final int C2SRoleInfo_Key_VALUE = 101;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PROTO_KEY valueOf(int value) {
      return forNumber(value);
    }

    public static PROTO_KEY forNumber(int value) {
      switch (value) {
        case 100: return Role_Key;
        case 101: return C2SRoleInfo_Key;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PROTO_KEY>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PROTO_KEY> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PROTO_KEY>() {
            public PROTO_KEY findValueByNumber(int number) {
              return PROTO_KEY.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return tiny.auto.proto.Enum.getDescriptor().getEnumTypes().get(0);
    }

    private static final PROTO_KEY[] VALUES = values();

    public static PROTO_KEY valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PROTO_KEY(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PROTO_KEY)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nenum.proto*.\n\tPROTO_KEY\022\014\n\010Role_Key\020d\022" +
      "\023\n\017C2SRoleInfo_Key\020eB\027\n\017tiny.auto.protoB" +
      "\004Enum"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
